import streamlit as st

se = st.text_input("Serum electrolytes - Mg: ")
cr = st.text_input("Creatinine - Mg/dl: ")
bu = st.text_input("Blood Urea Nitrogen(BUN) - Mg/dl: ")
bg = st.text_input("Blood Glucose Levels - Mg/dl: ")
lp = st.text_input("Lipid Profile - Mg/dl: ")
le = st.text_input("Liver Enzymes - u/l: ")
ch = st.text_input("Cholesterol - Mg/dl: ")
pa = st.text_input("Protein Albumin - g/dl: ")
pr = st.text_input("Prealbumin - Mg/dl: ")
tr = st.text_input("Trueransferrin - mcg/dl")
vb1 = st.text_input("vitamin B1 (thiamine) - mg:")
vb2 = st.text_input("Vitamin B2(riboflavin) - mg:")
vb3 = st.text_input("Vitamin B3(niacin) - mg:")
vb6 = st.text_input("Vitamin B6(Pyridoxine) - mg:")
vb9 = st.text_input("Vitamin B9(folic acid) - mg:")
vb12 = st.text_input("Vitamin B12(Cobalamin) - mg:")
va = st.text_input("Vitamin A - mg:")
vc = st.text_input("Vitamin C - mg:")
vd = st.text_input("Vitamin D - mg:")
ve = st.text_input("Vitamin E - mg:")
vk = st.text_input("Vitamin K - mg:")
iron = st.text_input("Iron - mg:")
zinc = st.text_input("Zinc - mg:")
sel = st.text_input("Selenium - mg:")