import streamlit as st


lb = st.selectbox('Low Body Weight:', ['Select Your Option','Yes', 'No'])
pb = st.selectbox('Prominent Bones:', ['Select Your Option','Yes', 'No'])
mw = st.selectbox('Muscle Wasting:', ['Select Your Option','Yes', 'No'])
ps = st.selectbox('Poor Skin Integrity:', ['Select Your Option','Yes', 'No'])
ds = st.selectbox('Dry skin:', ['Select Your Option','Yes', 'No'])
es = st.selectbox('Inelastic Skin:', ['Select Your Option','Yes', 'No'])
ra = st.selectbox('Rashes:', ['Select Your Option','Yes', 'No'])
ls = st.selectbox('Lesions:', ['Select Your Option','Yes', 'No'])
lsf = st.selectbox('Loss of Subcutaneous Fat tissue:', ['Select Your Option','Yes', 'No'])
lbt = st.selectbox('Low body temperature:', ['Select Your Option','Yes', 'No'])
lhr = st.selectbox('Low heart rate:', ['Select Your Option','Yes', 'No'])
bl = st.selectbox('blood pressure:', ['Select Your Option','Yes', 'No'])
co = st.selectbox('Constipation:', ['Select Your Option','Yes', 'No'])
deep = st.selectbox('Depression:', ['Select Your Option','Yes', 'No'])
face = st.selectbox('Thin arms and legs with edema in the abdomen and face:', ['Select Your Option','Yes', 'No'])
rhs = st.selectbox('Reduced handgrip strength:', ['Select Your Option','Yes', 'No'])
weak = st.selectbox('weakness:', ['Select Your Option','Yes', 'No'])
fathi = st.selectbox('FatigueIrritability:', ['Select Your Option','Yes', 'No'])
aoi = st.selectbox('Apathy, or inattention:', ['Select Your Option','Yes', 'No'])
pdh = st.selectbox('Poor dental health:', ['Select Your Option','Yes', 'No'])
bh = st.selectbox('Brittle hair:', ['Select Your Option','Yes', 'No'])
hlo = st.selectbox('hair loss:', ['Select Your Option','Yes', 'No'])
hc = st.selectbox('hair color loss:', ['Select Your Option','Yes', 'No'])
obi = st.selectbox('Obesity:', ['Select Your Option','Yes', 'No'])
nau = st.selectbox('nausea:', ['Select Your Option','Yes', 'No'])
vo = st.selectbox('vomiting:', ['Select Your Option','Yes', 'No'])
jp = st.selectbox('Joint pain :', ['Select Your Option','Yes', 'No'])
